In [11]:
# now we will learn about the combining function

import pandas as pd 

canadian_yt = pd.read_csv(r"C:\Users\HP\Documents\GitHub\Quant-Journey\month-01- python for finance\Week 2.0 - Pandas\CA_youtube_trending_data.csv", index_col = 0 , nrows = 500)
british_yt = pd.read_csv(r"C:\Users\HP\Documents\GitHub\Quant-Journey\month-01- python for finance\Week 2.0 - Pandas\BR_youtube_trending_data.csv" , index_col = 0 , nrows = 500 )

In [12]:
canadian_yt.head()

,title,publishedAt,channelId,channelTitle,categoryId,trending_date,tags,view_count,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,description
video_id,,,,,,,,,,,,,,,
KX06ksuS6Xo,Diljit Dosanjh: CLASH (Official) Music Video |...,2020-08-11T07:30:02Z,UCZRdNleCgW-BGUJf-bbjzQg,Diljit Dosanjh,10,2020-08-12T00:00:00Z,clash diljit dosanjh|diljit dosanjh|diljit dos...,9140911,296541,6180,30059,https://i.ytimg.com/vi/KX06ksuS6Xo/default.jpg,False,False,CLASH official music video performed by DILJIT...
J78aPJ3VyNs,I left youtube for a month and THIS is what ha...,2020-08-11T16:34:06Z,UCYzPXprvl5Y-Sf0g4vX-m6g,jacksepticeye,24,2020-08-12T00:00:00Z,jacksepticeye|funny|funny meme|memes|jacksepti...,2038853,353797,2628,40222,https://i.ytimg.com/vi/J78aPJ3VyNs/default.jpg,False,False,I left youtube for a month and this is what ha...
M9Pmf9AB4Mo,Apex Legends | Stories from the Outlands – “Th...,2020-08-11T17:00:10Z,UC0ZV6M2THA81QT9hrVWJG3A,Apex Legends,20,2020-08-12T00:00:00Z,Apex Legends|Apex Legends characters|new Apex ...,2381688,146740,2794,16549,https://i.ytimg.com/vi/M9Pmf9AB4Mo/default.jpg,False,False,"While running her own modding shop, Ramya Pare..."
3C66w5Z0ixs,I ASKED HER TO BE MY GIRLFRIEND...,2020-08-11T19:20:14Z,UCvtRTOMP2TqYqu51xNrqAzg,Brawadis,22,2020-08-12T00:00:00Z,brawadis|prank|basketball|skits|ghost|funny vi...,1514614,156914,5857,35331,https://i.ytimg.com/vi/3C66w5Z0ixs/default.jpg,False,False,SUBSCRIBE to BRAWADIS ▶ http://bit.ly/Subscrib...
VIUo6yapDbc,Ultimate DIY Home Movie Theater for The LaBran...,2020-08-11T15:10:05Z,UCDVPcEbVLQgLZX0Rt6jo34A,Mr. Kate,26,2020-08-12T00:00:00Z,The LaBrant Family|DIY|Interior Design|Makeove...,1123889,45803,964,2198,https://i.ytimg.com/vi/VIUo6yapDbc/default.jpg,False,False,Transforming The LaBrant Family's empty white ...

In [13]:
british_yt.head()

,title,publishedAt,channelId,channelTitle,categoryId,trending_date,tags,view_count,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,description
video_id,,,,,,,,,,,,,,,
s9FH4rDMvds,LEVEI UM FORA? FINGI ESTAR APAIXONADO POR ELA!,2020-08-11T22:21:49Z,UCGfBwrCoi9ZJjKiUK8MmJNw,Pietro Guedes,22,2020-08-12T00:00:00Z,pietro|guedes|ingrid|ohara|pingrid|vlog|amigos...,263835,85095,487,4500,https://i.ytimg.com/vi/s9FH4rDMvds/default.jpg,False,False,"Salve rapaziada, neste vídeo me declarei pra e..."
jbGRowa5tIk,ITZY “Not Shy” M/V TEASER,2020-08-11T15:00:13Z,UCaO6TYtlC8U5ttz62hTrZgg,JYP Entertainment,10,2020-08-12T00:00:00Z,JYP Entertainment|JYP|ITZY|있지|ITZY Video|ITZY ...,6000070,714310,15176,31040,https://i.ytimg.com/vi/jbGRowa5tIk/default.jpg,False,False,ITZY Not Shy M/V[ITZY Official] https://www.yo...
3EfkCrXKZNs,Oh Juliana PARÓDIA - MC Niack,2020-08-10T14:59:00Z,UCoXZmVma073v5G1cW82UKkA,As Irmãs Mota,22,2020-08-12T00:00:00Z,OH JULIANA PARÓDIA|MC Niack PARÓDIA|PARÓDIAS|A...,2296748,39761,5484,0,https://i.ytimg.com/vi/3EfkCrXKZNs/default.jpg,True,False,Se inscrevam meus amores! 📬 Quer nos mandar al...
gBjox7vn3-g,Contos de Runeterra: Targon | A Estrada Tortuosa,2020-08-11T15:00:09Z,UC6Xqz2pm50gDCORYztqhDpg,League of Legends BR,20,2020-08-12T00:00:00Z,Riot|Riot Games|League of Legends|lol|trailer|...,300510,46222,242,2748,https://i.ytimg.com/vi/gBjox7vn3-g/default.jpg,False,False,Você se unirá aos Lunari e aos Solari em Targo...
npoUGx7UW7o,Entrevista com Thammy Miranda | The Noite (10/...,2020-08-11T20:04:02Z,UCEWOoncsrmirqnFqxer9lmA,The Noite com Danilo Gentili,23,2020-08-12T00:00:00Z,The Noite|The Noite com Danilo Gentili|Danilo ...,327235,22059,3972,2751,https://i.ytimg.com/vi/npoUGx7UW7o/default.jpg,False,False,Danilo Gentili recebe Thammy Miranda. Após pas...

In [14]:
# we use .concat() when we have the column name in the csv's as same i.e. it just add up the rows
pd.concat( [ canadian_yt , british_yt ] )

,title,publishedAt,channelId,channelTitle,categoryId,trending_date,tags,view_count,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,description
video_id,,,,,,,,,,,,,,,
KX06ksuS6Xo,Diljit Dosanjh: CLASH (Official) Music Video |...,2020-08-11T07:30:02Z,UCZRdNleCgW-BGUJf-bbjzQg,Diljit Dosanjh,10,2020-08-12T00:00:00Z,clash diljit dosanjh|diljit dosanjh|diljit dos...,9140911,296541,6180,30059,https://i.ytimg.com/vi/KX06ksuS6Xo/default.jpg,False,False,CLASH official music video performed by DILJIT...
J78aPJ3VyNs,I left youtube for a month and THIS is what ha...,2020-08-11T16:34:06Z,UCYzPXprvl5Y-Sf0g4vX-m6g,jacksepticeye,24,2020-08-12T00:00:00Z,jacksepticeye|funny|funny meme|memes|jacksepti...,2038853,353797,2628,40222,https://i.ytimg.com/vi/J78aPJ3VyNs/default.jpg,False,False,I left youtube for a month and this is what ha...
M9Pmf9AB4Mo,Apex Legends | Stories from the Outlands – “Th...,2020-08-11T17:00:10Z,UC0ZV6M2THA81QT9hrVWJG3A,Apex Legends,20,2020-08-12T00:00:00Z,Apex Legends|Apex Legends characters|new Apex ...,2381688,146740,2794,16549,https://i.ytimg.com/vi/M9Pmf9AB4Mo/default.jpg,False,False,"While running her own modding shop, Ramya Pare..."
3C66w5Z0ixs,I ASKED HER TO BE MY GIRLFRIEND...,2020-08-11T19:20:14Z,UCvtRTOMP2TqYqu51xNrqAzg,Brawadis,22,2020-08-12T00:00:00Z,brawadis|prank|basketball|skits|ghost|funny vi...,1514614,156914,5857,35331,https://i.ytimg.com/vi/3C66w5Z0ixs/default.jpg,False,False,SUBSCRIBE to BRAWADIS ▶ http://bit.ly/Subscrib...
VIUo6yapDbc,Ultimate DIY Home Movie Theater for The LaBran...,2020-08-11T15:10:05Z,UCDVPcEbVLQgLZX0Rt6jo34A,Mr. Kate,26,2020-08-12T00:00:00Z,The LaBrant Family|DIY|Interior Design|Makeove...,1123889,45803,964,2198,https://i.ytimg.com/vi/VIUo6yapDbc/default.jpg,False,False,Transforming The LaBrant Family's empty white ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7WLXWPUTNJo,CONTEI PARA O MEU NAMORADO QUE ESTOU GRÁVIDA E...,2020-08-09T22:00:01Z,UCsaB2VrLZrtGbum6Eo0ClbA,Virgínia Fonseca,22,2020-08-14T00:00:00Z,vih|virginia|fonseca|virginia fonseca|rezende|...,3959528,395549,18545,13803,https://i.ytimg.com/vi/7WLXWPUTNJo/default.jpg,False,False,"Oiii amigos, agora os videos serão postados to..."
XNr1STGkOBc,Alva - Recomeço [Prod. Leo Ost],2020-08-11T15:05:21Z,UCS7mVK5en3RJ0PTbJiKXmzQ,Rap Box,10,2020-08-14T00:00:00Z,alva|alva flex|batalha da aldeia|aldeia record...,66633,11653,170,789,https://i.ytimg.com/vi/XNr1STGkOBc/default.jpg,False,False,Alva lança aqui no Rap Box seu primeiro trabal...
GtDqeelomsM,ESTUDOS & COMIDINHAS 📚🍃 [você vai amar],2020-08-12T14:30:00Z,UCv_Z66BB2xiAr9mrFurZ8Sg,Luana Carolina,27,2020-08-14T00:00:00Z,rotina de estudos|como ser mais produtivo|como...,97881,21400,129,1152,https://i.ytimg.com/vi/GtDqeelomsM/default.jpg,False,False,músicas:- New beginning [prod yung quiet]- And...
822wcYL_G3U,DICAS #2 RODADA | CARTOLA FC 2020 | BORA SEGUI...,2020-08-10T21:01:59Z,UC73iRP94nnZ5C3SE8zrBQaQ,BetinGamer,17,2020-08-14T00:00:00Z,betin|betingamer|cartola fc 2020|cartola 2020|...,301036,27215,313,1139,https://i.ytimg.com/vi/822wcYL_G3U/default.jpg,False,False,★DICAS EXTRAS BETIN 2020 - PLANO DE SÓCIOS:✅🤝🏻...
7lXDcPuIQbM,"PEGO, PENSO OU PASSO POLÊMICO!!! FT ANA MOSCO...",2020-08-10T21:00:01Z,UCKqECcpwgxXfWMskJHj9JEA,Ca Garcia,24,2020-08-14T00:00:00Z,carol|carol garcia|carolzinha|adr|rezende|reze...,377586,50752,644,1280,https://i.ytimg.com/vi/7lXDcPuIQbM/default.jpg,False,False,"EAIII AMORES, BELEZA? COMO VOCÊS ESTÃO??? ESPE..."

In [16]:
# now we will use the join()

left = canadian_yt.set_index(['title' , 'trending_date'])
left

,,publishedAt,channelId,channelTitle,categoryId,tags,view_count,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,description
title,trending_date,,,,,,,,,,,,,
Diljit Dosanjh: CLASH (Official) Music Video | G.O.A.T.,2020-08-12T00:00:00Z,2020-08-11T07:30:02Z,UCZRdNleCgW-BGUJf-bbjzQg,Diljit Dosanjh,10,clash diljit dosanjh|diljit dosanjh|diljit dos...,9140911,296541,6180,30059,https://i.ytimg.com/vi/KX06ksuS6Xo/default.jpg,False,False,CLASH official music video performed by DILJIT...
I left youtube for a month and THIS is what happened.,2020-08-12T00:00:00Z,2020-08-11T16:34:06Z,UCYzPXprvl5Y-Sf0g4vX-m6g,jacksepticeye,24,jacksepticeye|funny|funny meme|memes|jacksepti...,2038853,353797,2628,40222,https://i.ytimg.com/vi/J78aPJ3VyNs/default.jpg,False,False,I left youtube for a month and this is what ha...
Apex Legends | Stories from the Outlands – “The Endorsement”,2020-08-12T00:00:00Z,2020-08-11T17:00:10Z,UC0ZV6M2THA81QT9hrVWJG3A,Apex Legends,20,Apex Legends|Apex Legends characters|new Apex ...,2381688,146740,2794,16549,https://i.ytimg.com/vi/M9Pmf9AB4Mo/default.jpg,False,False,"While running her own modding shop, Ramya Pare..."
I ASKED HER TO BE MY GIRLFRIEND...,2020-08-12T00:00:00Z,2020-08-11T19:20:14Z,UCvtRTOMP2TqYqu51xNrqAzg,Brawadis,22,brawadis|prank|basketball|skits|ghost|funny vi...,1514614,156914,5857,35331,https://i.ytimg.com/vi/3C66w5Z0ixs/default.jpg,False,False,SUBSCRIBE to BRAWADIS ▶ http://bit.ly/Subscrib...
Ultimate DIY Home Movie Theater for The LaBrant Family!,2020-08-12T00:00:00Z,2020-08-11T15:10:05Z,UCDVPcEbVLQgLZX0Rt6jo34A,Mr. Kate,26,The LaBrant Family|DIY|Interior Design|Makeove...,1123889,45803,964,2198,https://i.ytimg.com/vi/VIUo6yapDbc/default.jpg,False,False,Transforming The LaBrant Family's empty white ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"TRAIL BLAZERS at MAVERICKS | FULL GAME HIGHLIGHTS | August 11, 2020",2020-08-14T00:00:00Z,2020-08-12T01:27:17Z,UCWJ2lWNubArHWmf3FIHbfcQ,NBA,17,NBA|G League|Basketball|game-0021901300|Jump S...,1170291,11359,442,3424,https://i.ytimg.com/vi/Aur7UgTGlL0/default.jpg,False,False,TRAIL BLAZERS at MAVERICKS | FULL GAME HIGHLIG...
Veggie & Fish Tank,2020-08-14T00:00:00Z,2020-08-11T11:08:04Z,UCRxAgfYexGLlu1WHGIMUDqw,JunsKitchen,26,taking|cats|walk|jun|junskitchen|juns kitchen|...,511930,71920,202,3842,https://i.ytimg.com/vi/JJk1ji23Ey8/default.jpg,False,False,I've been wanting to do aquaponics (growing ve...
Every Drive Thru Ever,2020-08-14T00:00:00Z,2020-08-10T16:00:17Z,UCY30JRSgfhYXA6i6xX1erWg,Smosh,23,smosh|smosh pit|smosh games|funny|comedy|Every...,892033,53167,1267,3802,https://i.ytimg.com/vi/vml4hskxqtE/default.jpg,False,False,Because fast food needed to be even MORE conve...
Being replaced.,2020-08-14T00:00:00Z,2020-08-10T20:56:04Z,UCFp65-s_fyaBjVZbVyp--Kw,Gabrielle Moses,22,jack and gab|jack and gab breakup|Gabrielle mo...,653240,46324,5814,11796,https://i.ytimg.com/vi/PT6hPvOqTYc/default.jpg,False,False,Just wanted to let you guys how I really feel ...
Addressing RUMORS About Me While Testing New Makeup,2020-08-14T00:00:00Z,2020-08-09T19:00:30Z,UCkvK_5omS-42Ovgah8KRKtg,jeffreestar,26,jeffree star|jeffree star cosmetics|patrick st...,3775049,155631,68385,34731,https://i.ytimg.com/vi/GGEBtW2mWOk/default.jpg,False,False,Today I'm testing out ALL brand new makeup whi...

In [18]:
right = british_yt.set_index(['title','trending_date'])
right

,,publishedAt,channelId,channelTitle,categoryId,tags,view_count,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,description
title,trending_date,,,,,,,,,,,,,
LEVEI UM FORA? FINGI ESTAR APAIXONADO POR ELA!,2020-08-12T00:00:00Z,2020-08-11T22:21:49Z,UCGfBwrCoi9ZJjKiUK8MmJNw,Pietro Guedes,22,pietro|guedes|ingrid|ohara|pingrid|vlog|amigos...,263835,85095,487,4500,https://i.ytimg.com/vi/s9FH4rDMvds/default.jpg,False,False,"Salve rapaziada, neste vídeo me declarei pra e..."
ITZY “Not Shy” M/V TEASER,2020-08-12T00:00:00Z,2020-08-11T15:00:13Z,UCaO6TYtlC8U5ttz62hTrZgg,JYP Entertainment,10,JYP Entertainment|JYP|ITZY|있지|ITZY Video|ITZY ...,6000070,714310,15176,31040,https://i.ytimg.com/vi/jbGRowa5tIk/default.jpg,False,False,ITZY Not Shy M/V[ITZY Official] https://www.yo...
Oh Juliana PARÓDIA - MC Niack,2020-08-12T00:00:00Z,2020-08-10T14:59:00Z,UCoXZmVma073v5G1cW82UKkA,As Irmãs Mota,22,OH JULIANA PARÓDIA|MC Niack PARÓDIA|PARÓDIAS|A...,2296748,39761,5484,0,https://i.ytimg.com/vi/3EfkCrXKZNs/default.jpg,True,False,Se inscrevam meus amores! 📬 Quer nos mandar al...
Contos de Runeterra: Targon | A Estrada Tortuosa,2020-08-12T00:00:00Z,2020-08-11T15:00:09Z,UC6Xqz2pm50gDCORYztqhDpg,League of Legends BR,20,Riot|Riot Games|League of Legends|lol|trailer|...,300510,46222,242,2748,https://i.ytimg.com/vi/gBjox7vn3-g/default.jpg,False,False,Você se unirá aos Lunari e aos Solari em Targo...
Entrevista com Thammy Miranda | The Noite (10/08/20),2020-08-12T00:00:00Z,2020-08-11T20:04:02Z,UCEWOoncsrmirqnFqxer9lmA,The Noite com Danilo Gentili,23,The Noite|The Noite com Danilo Gentili|Danilo ...,327235,22059,3972,2751,https://i.ytimg.com/vi/npoUGx7UW7o/default.jpg,False,False,Danilo Gentili recebe Thammy Miranda. Após pas...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
CONTEI PARA O MEU NAMORADO QUE ESTOU GRÁVIDA E TIVE UMA SURPRESA!!,2020-08-14T00:00:00Z,2020-08-09T22:00:01Z,UCsaB2VrLZrtGbum6Eo0ClbA,Virgínia Fonseca,22,vih|virginia|fonseca|virginia fonseca|rezende|...,3959528,395549,18545,13803,https://i.ytimg.com/vi/7WLXWPUTNJo/default.jpg,False,False,"Oiii amigos, agora os videos serão postados to..."
Alva - Recomeço [Prod. Leo Ost],2020-08-14T00:00:00Z,2020-08-11T15:05:21Z,UCS7mVK5en3RJ0PTbJiKXmzQ,Rap Box,10,alva|alva flex|batalha da aldeia|aldeia record...,66633,11653,170,789,https://i.ytimg.com/vi/XNr1STGkOBc/default.jpg,False,False,Alva lança aqui no Rap Box seu primeiro trabal...
ESTUDOS & COMIDINHAS 📚🍃 [você vai amar],2020-08-14T00:00:00Z,2020-08-12T14:30:00Z,UCv_Z66BB2xiAr9mrFurZ8Sg,Luana Carolina,27,rotina de estudos|como ser mais produtivo|como...,97881,21400,129,1152,https://i.ytimg.com/vi/GtDqeelomsM/default.jpg,False,False,músicas:- New beginning [prod yung quiet]- And...
DICAS #2 RODADA | CARTOLA FC 2020 | BORA SEGUIR VALORIZANDO E MITANDO!,2020-08-14T00:00:00Z,2020-08-10T21:01:59Z,UC73iRP94nnZ5C3SE8zrBQaQ,BetinGamer,17,betin|betingamer|cartola fc 2020|cartola 2020|...,301036,27215,313,1139,https://i.ytimg.com/vi/822wcYL_G3U/default.jpg,False,False,★DICAS EXTRAS BETIN 2020 - PLANO DE SÓCIOS:✅🤝🏻...
"PEGO, PENSO OU PASSO POLÊMICO!!! FT ANA MOSCONI E LAIS BIANCHESSI",2020-08-14T00:00:00Z,2020-08-10T21:00:01Z,UCKqECcpwgxXfWMskJHj9JEA,Ca Garcia,24,carol|carol garcia|carolzinha|adr|rezende|reze...,377586,50752,644,1280,https://i.ytimg.com/vi/7lXDcPuIQbM/default.jpg,False,False,"EAIII AMORES, BELEZA? COMO VOCÊS ESTÃO??? ESPE..."

In [19]:
# now we will use the join() function which will join based on the rows index 

# I have created a variable 'left' which have the index 'title' and 'trending_date'
# I have created a variable 'right' which have the index 'title' and 'trending_date'

left.join( right , lsuffix = '_CAN' , rsuffix = '_UK' )

,,publishedAt_CAN,channelId_CAN,channelTitle_CAN,categoryId_CAN,tags_CAN,view_count_CAN,likes_CAN,dislikes_CAN,comment_count_CAN,thumbnail_link_CAN,...,categoryId_UK,tags_UK,view_count_UK,likes_UK,dislikes_UK,comment_count_UK,thumbnail_link_UK,comments_disabled_UK,ratings_disabled_UK,description_UK
title,trending_date,,,,,,,,,,,,,,,,,,,,,
Diljit Dosanjh: CLASH (Official) Music Video | G.O.A.T.,2020-08-12T00:00:00Z,2020-08-11T07:30:02Z,UCZRdNleCgW-BGUJf-bbjzQg,Diljit Dosanjh,10,clash diljit dosanjh|diljit dosanjh|diljit dos...,9140911,296541,6180,30059,https://i.ytimg.com/vi/KX06ksuS6Xo/default.jpg,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
I left youtube for a month and THIS is what happened.,2020-08-12T00:00:00Z,2020-08-11T16:34:06Z,UCYzPXprvl5Y-Sf0g4vX-m6g,jacksepticeye,24,jacksepticeye|funny|funny meme|memes|jacksepti...,2038853,353797,2628,40222,https://i.ytimg.com/vi/J78aPJ3VyNs/default.jpg,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Apex Legends | Stories from the Outlands – “The Endorsement”,2020-08-12T00:00:00Z,2020-08-11T17:00:10Z,UC0ZV6M2THA81QT9hrVWJG3A,Apex Legends,20,Apex Legends|Apex Legends characters|new Apex ...,2381688,146740,2794,16549,https://i.ytimg.com/vi/M9Pmf9AB4Mo/default.jpg,...,20.0,Apex Legends|Apex Legends characters|new Apex ...,2381688.0,146743.0,2794.0,16558.0,https://i.ytimg.com/vi/M9Pmf9AB4Mo/default.jpg,False,False,"While running her own modding shop, Ramya Pare..."
I ASKED HER TO BE MY GIRLFRIEND...,2020-08-12T00:00:00Z,2020-08-11T19:20:14Z,UCvtRTOMP2TqYqu51xNrqAzg,Brawadis,22,brawadis|prank|basketball|skits|ghost|funny vi...,1514614,156914,5857,35331,https://i.ytimg.com/vi/3C66w5Z0ixs/default.jpg,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Ultimate DIY Home Movie Theater for The LaBrant Family!,2020-08-12T00:00:00Z,2020-08-11T15:10:05Z,UCDVPcEbVLQgLZX0Rt6jo34A,Mr. Kate,26,The LaBrant Family|DIY|Interior Design|Makeove...,1123889,45803,964,2198,https://i.ytimg.com/vi/VIUo6yapDbc/default.jpg,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"TRAIL BLAZERS at MAVERICKS | FULL GAME HIGHLIGHTS | August 11, 2020",2020-08-14T00:00:00Z,2020-08-12T01:27:17Z,UCWJ2lWNubArHWmf3FIHbfcQ,NBA,17,NBA|G League|Basketball|game-0021901300|Jump S...,1170291,11359,442,3424,https://i.ytimg.com/vi/Aur7UgTGlL0/default.jpg,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Veggie & Fish Tank,2020-08-14T00:00:00Z,2020-08-11T11:08:04Z,UCRxAgfYexGLlu1WHGIMUDqw,JunsKitchen,26,taking|cats|walk|jun|junskitchen|juns kitchen|...,511930,71920,202,3842,https://i.ytimg.com/vi/JJk1ji23Ey8/default.jpg,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Every Drive Thru Ever,2020-08-14T00:00:00Z,2020-08-10T16:00:17Z,UCY30JRSgfhYXA6i6xX1erWg,Smosh,23,smosh|smosh pit|smosh games|funny|comedy|Every...,892033,53167,1267,3802,https://i.ytimg.com/vi/vml4hskxqtE/default.jpg,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Being replaced.,2020-08-14T00:00:00Z,2020-08-10T20:56:04Z,UCFp65-s_fyaBjVZbVyp--Kw,Gabrielle Moses,22,jack and gab|jack and gab breakup|Gabrielle mo...,653240,46324,5814,11796,https://i.ytimg.com/vi/PT6hPvOqTYc/default.jpg,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Addressing RUMORS About Me While Testing New Makeup,2020-08-14T00:00:00Z,2020-08-09T19:00:30Z,UCkvK_5omS-42Ovgah8KRKtg,jeffreestar,26,jeffree star|jeffree star cosmetics|patrick st...,3775049,155631,68385,34731,https://i.ytimg.com/vi/GGEBtW2mWOk/default.jpg,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN